apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
  finalizers:
    # This finalizer is for demo purposes, in production remove apps using argocd CLI "argocd app delete workload --cascade"
    # When you invoke argocd app delete with --cascade, the finalizer is added automatically.
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 57.2.0
    chart: kube-prometheus-stack
    helm:
      values: |
        grafana:
          ingress: 
            enabled: true
            ingressClassName: alb
            annotations: 
              alb.ingress.kubernetes.io/scheme: internet-facing
              alb.ingress.kubernetes.io/target-type: ip
              alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}]'
            path: /
            hosts:
              - <hostname> 
         
  destination:
    server: https://kubernetes.default.svc
    namespace: prometheus
  syncPolicy:
    automated:
      allowEmpty: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
    retry:
      limit: 60
